name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # main 브랜치에 push될 때 실행

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # GitHub 리포지토리 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3

      # Node.js 설정 (14.x 이상 버전 필요)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # 프로젝트 의존성 설치
      - name: Install dependencies
        run: npm install

      # Vite로 빌드 실행
      - name: Build project
        run: npm run build

      # dist 폴더를 GitHub Pages에 배포
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
